### ISSUE TITLE
Medium: Entering SDK when device is in landscape mode

### ISSUE THREAD

**Issue by itscam** [printdotio/printio-ios-sdk#395]
I believe this was an issue that we discussed before. The SDK does not currently handle landscape mode properly. If a user has their device in landscape mode or even slightly off-kilter, the SDK will open in this state. It also does not switch back to portrait mode when rotating the device.

Is there anything we can do to keep this from happening?

![img_0309](https://cloud.githubusercontent.com/assets/8051364/6631820/fa73e0f6-c8f1-11e4-9077-6d8e38e109c5.PNG)
![img_0308](https://cloud.githubusercontent.com/assets/8051364/6631818/fa72f60a-c8f1-11e4-94ce-691e907b7d18.PNG)
![img_0306](https://cloud.githubusercontent.com/assets/8051364/6631819/fa73736e-c8f1-11e4-9603-3c7297907ee9.PNG)

**Comment by AustenB** [comment]
@itscam we remember this issue. Not sure of right fix for it.

**Comment by itscam** [comment]
@AustenB Issues if the device is rotated and you tap to edit a photo, the editor loads in landscape mode but doesn't fit the screen. When you leave the editor, the preview is broken, and your only option is to close the app.

![img_0279](https://cloud.githubusercontent.com/assets/8051364/6671103/a6c855c0-cbc8-11e4-89ae-7b895124d175.PNG)
![img_0272](https://cloud.githubusercontent.com/assets/8051364/6671066/687dcd5e-cbc8-11e4-881d-4c59065b1188.PNG)

**Comment by AustenB** [comment]
Also for all tickets - can you include which Phone you are testing on?

On Mon, Mar 16, 2015 at 12:40 PM, Cameron Bradley <notifications@github.com>
wrote:

> @AustenB <https://github.com/AustenB> Issues if the device is rotated and
> you tap to edit a photo, the editor loads in landscape mode but doesn't fit
> the screen. When you leave the editor, the preview is broken, and your only
> option is to close the app.
>
> [image: img_0279]
> <https://cloud.githubusercontent.com/assets/8051364/6671103/a6c855c0-cbc8-11e4-89ae-7b895124d175.PNG>
> [image: img_0272]
> <https://cloud.githubusercontent.com/assets/8051364/6671066/687dcd5e-cbc8-11e4-881d-4c59065b1188.PNG>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/395#issuecomment-81785722>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by itscam** [comment]
This is an issue for all iPhones.

**Comment by AustenB** [comment]
I know but im saying in general -> if you could include it - that would be
awesome.

All of the bugs you found are fixed in next release (or have an init code
issue) -> landscape rotation is something we are trying to replicate
outside of your app

On Mon, Mar 16, 2015 at 12:43 PM, Cameron Bradley <notifications@github.com>
wrote:

> This is an issue for all iPhones.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/printdotio/printio-ios-sdk/issues/395#issuecomment-81789072>
> .
>



-- 
Austen Bernstein
Founder & CEO
printio

**Comment by perisicboro** [comment]
@AustenB @itscam Fixed. I will upload new dev build later today, v1.1.5-dev

**Comment by itscam** [comment]
@AustenB @perisicboro Were these changes in 1.1.9? We are still seeing the same issue.

**Comment by AustenB** [comment]
@itscam let us know if the changes were made

**Comment by itscam** [comment]
@AustenB @perisicboro Inside the SDK, I am no longer seeing the same landscape issues. However, when launching the SDK from a landscape orientation, there are still issues. Is there something we can do to block landscape during launch?

**Comment by AustenB** [comment]
This is a separate issue with making it.

You will need landscape turned on for photo books btw
